sudo: required
services:
  - docker

before_install:
  - docker build -t alexandrusimionovro/docker-react-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true alexandrusimionovro/docker-react-ci npm run test -- --coverage