sudo: required
services:
  - docker

before_install:
  - docker build -t alexandrusimionovro/docker-react-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true alexandrusimionovro/docker-react-ci npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2" 
  app: "ReactJS-App-Project"
  env: "ReactjsAppProject-env"
  bucket_name: "elasticbeanstalk-us-east-2-945523477108"
  bucket_path: "ReactJS-App-Project"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
