sudo: required
services:
  - docker

before_install:
  - docker build -t AlexandruSimionovRO/docker-react -f Dockerfile.dev .

script:
  - docker run AlexandruSimionovRO/docker-react npm run test -- --coverage 
